# Generated by bravado-types 1.0.1
# Timestamp: 2022-10-21 19:14:19.528003+00:00
# Schema version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
# Schema origin url: https://www.cbioportal.org/api/v2/api-docs
# Bravado version: 11.0.3
# Bravado-core version: 5.17.1
# type: ignore
# pylint: disable = too-few-public-methods

"""CBioPortal types."""

import sys

from bravado.client import SwaggerClient

__all__ = [
    "CBioPortalSwaggerClient",
    "Cancer_TypesResource",
    "Clinical_AttributesResource",
    "Clinical_DataResource",
    "Copy_Number_SegmentsResource",
    "Discrete_Copy_Number_AlterationsResource",
    "Gene_Panel_DataResource",
    "Gene_PanelsResource",
    "Generic_Assay_DataResource",
    "Generic_AssaysResource",
    "GenesResource",
    "InfoResource",
    "Molecular_DataResource",
    "Molecular_ProfilesResource",
    "MutationsResource",
    "PatientsResource",
    "Sample_ListsResource",
    "SamplesResource",
    "Server_running_statusResource",
    "StudiesResource",
    "TreatmentsResource",
    "fetchAllClinicalDataInStudyUsingPOSTOperation",
    "fetchAllMolecularDataInMolecularProfileUsingPOSTOperation",
    "fetchClinicalAttributesUsingPOSTOperation",
    "fetchClinicalDataUsingPOSTOperation",
    "fetchCopyNumberSegmentsUsingPOSTOperation",
    "fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTOperation",
    "fetchGenePanelDataInMultipleMolecularProfilesUsingPOSTOperation",
    "fetchGenePanelsUsingPOSTOperation",
    "fetchGenericAssayDataInMolecularProfileUsingPOSTOperation",
    "fetchGenericAssayDataInMultipleMolecularProfilesUsingPOSTOperation",
    "fetchGenericAssayMetaUsingPOSTOperation",
    "fetchGenesUsingPOSTOperation",
    "fetchMolecularDataInMultipleMolecularProfilesUsingPOSTOperation",
    "fetchMolecularProfilesUsingPOSTOperation",
    "fetchMutationsInMolecularProfileUsingPOSTOperation",
    "fetchMutationsInMultipleMolecularProfilesUsingPOSTOperation",
    "fetchPatientsUsingPOSTOperation",
    "fetchSampleListsUsingPOSTOperation",
    "fetchSamplesUsingPOSTOperation",
    "fetchStudiesUsingPOSTOperation",
    "getAliasesOfGeneUsingGETOperation",
    "getAllCancerTypesUsingGETOperation",
    "getAllClinicalAttributesInStudyUsingGETOperation",
    "getAllClinicalAttributesUsingGETOperation",
    "getAllClinicalDataInStudyUsingGETOperation",
    "getAllClinicalDataOfPatientInStudyUsingGETOperation",
    "getAllClinicalDataOfSampleInStudyUsingGETOperation",
    "getAllGenePanelsUsingGETOperation",
    "getAllGenesUsingGETOperation",
    "getAllMolecularDataInMolecularProfileUsingGETOperation",
    "getAllMolecularProfilesInStudyUsingGETOperation",
    "getAllMolecularProfilesUsingGETOperation",
    "getAllPatientTreatmentsUsingPOSTOperation",
    "getAllPatientsInStudyUsingGETOperation",
    "getAllPatientsUsingGETOperation",
    "getAllSampleIdsInSampleListUsingGETOperation",
    "getAllSampleListsInStudyUsingGETOperation",
    "getAllSampleListsUsingGETOperation",
    "getAllSampleTreatmentsUsingPOSTOperation",
    "getAllSamplesInStudyUsingGETOperation",
    "getAllSamplesOfPatientInStudyUsingGETOperation",
    "getAllStudiesUsingGETOperation",
    "getCancerTypeUsingGETOperation",
    "getClinicalAttributeInStudyUsingGETOperation",
    "getContainsSampleTreatmentDataUsingPOSTOperation",
    "getContainsTreatmentDataUsingPOSTOperation",
    "getCopyNumberSegmentsInSampleInStudyUsingGETOperation",
    "getDiscreteCopyNumbersInMolecularProfileUsingGETOperation",
    "getGenePanelDataUsingPOSTOperation",
    "getGenePanelUsingGETOperation",
    "getGeneUsingGETOperation",
    "getGenericAssayDataInMolecularProfileUsingGETOperation",
    "getGenericAssayMetaUsingGETOperation",
    "getGenericAssayMeta_gaUsingGETOperation",
    "getInfoUsingGETOperation",
    "getMolecularProfileUsingGETOperation",
    "getMutationsInMolecularProfileBySampleListIdUsingGETOperation",
    "getPatientInStudyUsingGETOperation",
    "getSampleInStudyUsingGETOperation",
    "getSampleListUsingGETOperation",
    "getSamplesByKeywordUsingGETOperation",
    "getServerStatusUsingGETOperation",
    "getStudyUsingGETOperation",
    "getTagsForMultipleStudiesUsingPOSTOperation",
    "getTagsUsingGETOperation",
    "AlleleSpecificCopyNumberModel",
    "AlterationFilterModel",
    "AndedPatientTreatmentFiltersModel",
    "AndedSampleTreatmentFiltersModel",
    "CancerStudyModel",
    "CancerStudyTagsModel",
    "ClinicalAttributeModel",
    "ClinicalDataModel",
    "ClinicalDataFilterModel",
    "ClinicalDataIdentifierModel",
    "ClinicalDataMultiStudyFilterModel",
    "ClinicalDataSingleStudyFilterModel",
    "ClinicalEventSampleModel",
    "CopyNumberSegModel",
    "DataFilterValueModel",
    "DiscreteCopyNumberDataModel",
    "DiscreteCopyNumberFilterModel",
    "GeneModel",
    "GeneFilterModel",
    "GeneFilterQueryModel",
    "GenePanelModel",
    "GenePanelDataModel",
    "GenePanelDataFilterModel",
    "GenePanelDataMultipleStudyFilterModel",
    "GenePanelToGeneModel",
    "GenericAssayDataModel",
    "GenericAssayDataFilterModel",
    "GenericAssayDataMultipleStudyFilterModel",
    "GenericAssayFilterModel",
    "GenericAssayMetaModel",
    "GenericAssayMetaFilterModel",
    "GenomicDataFilterModel",
    "InfoModel",
    "MolecularDataFilterModel",
    "MolecularDataMultipleStudyFilterModel",
    "MolecularProfileModel",
    "MolecularProfileFilterModel",
    "MutationModel",
    "MutationFilterModel",
    "MutationMultipleStudyFilterModel",
    "NumericGeneMolecularDataModel",
    "OredPatientTreatmentFiltersModel",
    "OredSampleTreatmentFiltersModel",
    "PatientModel",
    "PatientFilterModel",
    "PatientIdentifierModel",
    "PatientTreatmentFilterModel",
    "PatientTreatmentRowModel",
    "SampleModel",
    "SampleFilterModel",
    "SampleIdentifierModel",
    "SampleListModel",
    "SampleMolecularIdentifierModel",
    "SampleTreatmentFilterModel",
    "SampleTreatmentRowModel",
    "ServerStatusMessageModel",
    "StudyViewFilterModel",
    "TypeOfCancerModel",
]

_TYPE_ERROR = "Generated types cannot be used for runtime type checks"
_RUNTIME_ERROR = "Generated types cannot be instantiated at runtime."


if sys.version_info >= (3, 7, 0):

    class _PlaceholderMeta(type):
        def __instancecheck__(cls, instance):
            raise TypeError(_TYPE_ERROR)

        def __subclasscheck__(cls, subclass):
            raise TypeError(_TYPE_ERROR)

    class _Placeholder(metaclass=_PlaceholderMeta):
        def __init__(self, *args, **kwargs):
            raise RuntimeError(_RUNTIME_ERROR)

    _PLACEHOLDER = _Placeholder
else:

    def _placeholder(*args, **kwargs):
        raise RuntimeError(_RUNTIME_ERROR)

    _PLACEHOLDER = _placeholder


# Client type


class CBioPortalSwaggerClient(SwaggerClient):
    """CBioPortal-specific Swagger client."""


# Resource types

Cancer_TypesResource = _PLACEHOLDER
Clinical_AttributesResource = _PLACEHOLDER
Clinical_DataResource = _PLACEHOLDER
Copy_Number_SegmentsResource = _PLACEHOLDER
Discrete_Copy_Number_AlterationsResource = _PLACEHOLDER
Gene_Panel_DataResource = _PLACEHOLDER
Gene_PanelsResource = _PLACEHOLDER
Generic_Assay_DataResource = _PLACEHOLDER
Generic_AssaysResource = _PLACEHOLDER
GenesResource = _PLACEHOLDER
InfoResource = _PLACEHOLDER
Molecular_DataResource = _PLACEHOLDER
Molecular_ProfilesResource = _PLACEHOLDER
MutationsResource = _PLACEHOLDER
PatientsResource = _PLACEHOLDER
Sample_ListsResource = _PLACEHOLDER
SamplesResource = _PLACEHOLDER
Server_running_statusResource = _PLACEHOLDER
StudiesResource = _PLACEHOLDER
TreatmentsResource = _PLACEHOLDER

# Operation types

fetchAllClinicalDataInStudyUsingPOSTOperation = _PLACEHOLDER
fetchAllMolecularDataInMolecularProfileUsingPOSTOperation = _PLACEHOLDER
fetchClinicalAttributesUsingPOSTOperation = _PLACEHOLDER
fetchClinicalDataUsingPOSTOperation = _PLACEHOLDER
fetchCopyNumberSegmentsUsingPOSTOperation = _PLACEHOLDER
fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTOperation = _PLACEHOLDER
fetchGenePanelDataInMultipleMolecularProfilesUsingPOSTOperation = _PLACEHOLDER
fetchGenePanelsUsingPOSTOperation = _PLACEHOLDER
fetchGenericAssayDataInMolecularProfileUsingPOSTOperation = _PLACEHOLDER
fetchGenericAssayDataInMultipleMolecularProfilesUsingPOSTOperation = _PLACEHOLDER
fetchGenericAssayMetaUsingPOSTOperation = _PLACEHOLDER
fetchGenesUsingPOSTOperation = _PLACEHOLDER
fetchMolecularDataInMultipleMolecularProfilesUsingPOSTOperation = _PLACEHOLDER
fetchMolecularProfilesUsingPOSTOperation = _PLACEHOLDER
fetchMutationsInMolecularProfileUsingPOSTOperation = _PLACEHOLDER
fetchMutationsInMultipleMolecularProfilesUsingPOSTOperation = _PLACEHOLDER
fetchPatientsUsingPOSTOperation = _PLACEHOLDER
fetchSampleListsUsingPOSTOperation = _PLACEHOLDER
fetchSamplesUsingPOSTOperation = _PLACEHOLDER
fetchStudiesUsingPOSTOperation = _PLACEHOLDER
getAliasesOfGeneUsingGETOperation = _PLACEHOLDER
getAllCancerTypesUsingGETOperation = _PLACEHOLDER
getAllClinicalAttributesInStudyUsingGETOperation = _PLACEHOLDER
getAllClinicalAttributesUsingGETOperation = _PLACEHOLDER
getAllClinicalDataInStudyUsingGETOperation = _PLACEHOLDER
getAllClinicalDataOfPatientInStudyUsingGETOperation = _PLACEHOLDER
getAllClinicalDataOfSampleInStudyUsingGETOperation = _PLACEHOLDER
getAllGenePanelsUsingGETOperation = _PLACEHOLDER
getAllGenesUsingGETOperation = _PLACEHOLDER
getAllMolecularDataInMolecularProfileUsingGETOperation = _PLACEHOLDER
getAllMolecularProfilesInStudyUsingGETOperation = _PLACEHOLDER
getAllMolecularProfilesUsingGETOperation = _PLACEHOLDER
getAllPatientTreatmentsUsingPOSTOperation = _PLACEHOLDER
getAllPatientsInStudyUsingGETOperation = _PLACEHOLDER
getAllPatientsUsingGETOperation = _PLACEHOLDER
getAllSampleIdsInSampleListUsingGETOperation = _PLACEHOLDER
getAllSampleListsInStudyUsingGETOperation = _PLACEHOLDER
getAllSampleListsUsingGETOperation = _PLACEHOLDER
getAllSampleTreatmentsUsingPOSTOperation = _PLACEHOLDER
getAllSamplesInStudyUsingGETOperation = _PLACEHOLDER
getAllSamplesOfPatientInStudyUsingGETOperation = _PLACEHOLDER
getAllStudiesUsingGETOperation = _PLACEHOLDER
getCancerTypeUsingGETOperation = _PLACEHOLDER
getClinicalAttributeInStudyUsingGETOperation = _PLACEHOLDER
getContainsSampleTreatmentDataUsingPOSTOperation = _PLACEHOLDER
getContainsTreatmentDataUsingPOSTOperation = _PLACEHOLDER
getCopyNumberSegmentsInSampleInStudyUsingGETOperation = _PLACEHOLDER
getDiscreteCopyNumbersInMolecularProfileUsingGETOperation = _PLACEHOLDER
getGenePanelDataUsingPOSTOperation = _PLACEHOLDER
getGenePanelUsingGETOperation = _PLACEHOLDER
getGeneUsingGETOperation = _PLACEHOLDER
getGenericAssayDataInMolecularProfileUsingGETOperation = _PLACEHOLDER
getGenericAssayMetaUsingGETOperation = _PLACEHOLDER
getGenericAssayMeta_gaUsingGETOperation = _PLACEHOLDER
getInfoUsingGETOperation = _PLACEHOLDER
getMolecularProfileUsingGETOperation = _PLACEHOLDER
getMutationsInMolecularProfileBySampleListIdUsingGETOperation = _PLACEHOLDER
getPatientInStudyUsingGETOperation = _PLACEHOLDER
getSampleInStudyUsingGETOperation = _PLACEHOLDER
getSampleListUsingGETOperation = _PLACEHOLDER
getSamplesByKeywordUsingGETOperation = _PLACEHOLDER
getServerStatusUsingGETOperation = _PLACEHOLDER
getStudyUsingGETOperation = _PLACEHOLDER
getTagsForMultipleStudiesUsingPOSTOperation = _PLACEHOLDER
getTagsUsingGETOperation = _PLACEHOLDER

# Model types

AlleleSpecificCopyNumberModel = _PLACEHOLDER
AlterationFilterModel = _PLACEHOLDER
AndedPatientTreatmentFiltersModel = _PLACEHOLDER
AndedSampleTreatmentFiltersModel = _PLACEHOLDER
CancerStudyModel = _PLACEHOLDER
CancerStudyTagsModel = _PLACEHOLDER
ClinicalAttributeModel = _PLACEHOLDER
ClinicalDataModel = _PLACEHOLDER
ClinicalDataFilterModel = _PLACEHOLDER
ClinicalDataIdentifierModel = _PLACEHOLDER
ClinicalDataMultiStudyFilterModel = _PLACEHOLDER
ClinicalDataSingleStudyFilterModel = _PLACEHOLDER
ClinicalEventSampleModel = _PLACEHOLDER
CopyNumberSegModel = _PLACEHOLDER
DataFilterValueModel = _PLACEHOLDER
DiscreteCopyNumberDataModel = _PLACEHOLDER
DiscreteCopyNumberFilterModel = _PLACEHOLDER
GeneModel = _PLACEHOLDER
GeneFilterModel = _PLACEHOLDER
GeneFilterQueryModel = _PLACEHOLDER
GenePanelModel = _PLACEHOLDER
GenePanelDataModel = _PLACEHOLDER
GenePanelDataFilterModel = _PLACEHOLDER
GenePanelDataMultipleStudyFilterModel = _PLACEHOLDER
GenePanelToGeneModel = _PLACEHOLDER
GenericAssayDataModel = _PLACEHOLDER
GenericAssayDataFilterModel = _PLACEHOLDER
GenericAssayDataMultipleStudyFilterModel = _PLACEHOLDER
GenericAssayFilterModel = _PLACEHOLDER
GenericAssayMetaModel = _PLACEHOLDER
GenericAssayMetaFilterModel = _PLACEHOLDER
GenomicDataFilterModel = _PLACEHOLDER
InfoModel = _PLACEHOLDER
MolecularDataFilterModel = _PLACEHOLDER
MolecularDataMultipleStudyFilterModel = _PLACEHOLDER
MolecularProfileModel = _PLACEHOLDER
MolecularProfileFilterModel = _PLACEHOLDER
MutationModel = _PLACEHOLDER
MutationFilterModel = _PLACEHOLDER
MutationMultipleStudyFilterModel = _PLACEHOLDER
NumericGeneMolecularDataModel = _PLACEHOLDER
OredPatientTreatmentFiltersModel = _PLACEHOLDER
OredSampleTreatmentFiltersModel = _PLACEHOLDER
PatientModel = _PLACEHOLDER
PatientFilterModel = _PLACEHOLDER
PatientIdentifierModel = _PLACEHOLDER
PatientTreatmentFilterModel = _PLACEHOLDER
PatientTreatmentRowModel = _PLACEHOLDER
SampleModel = _PLACEHOLDER
SampleFilterModel = _PLACEHOLDER
SampleIdentifierModel = _PLACEHOLDER
SampleListModel = _PLACEHOLDER
SampleMolecularIdentifierModel = _PLACEHOLDER
SampleTreatmentFilterModel = _PLACEHOLDER
SampleTreatmentRowModel = _PLACEHOLDER
ServerStatusMessageModel = _PLACEHOLDER
StudyViewFilterModel = _PLACEHOLDER
TypeOfCancerModel = _PLACEHOLDER
